### ISSUE TITLE
.gitignore patterns are not being honoured

### ISSUE THREAD

**Issue by princerachit** [autofix-dev/autofix#13]
Even after specifying a directory in .gitignore, autofix still raises PRs to fix dockerfiles in those dirs.

e.g. [.gitignore](https://github.com/gitpod-io/workspace-images/pull/678) entry and PRs raised [[1](https://github.com/gitpod-io/workspace-images/pull/748)][[2](https://github.com/gitpod-io/workspace-images/pull/747/files)]

**Comment by jankeromnes** [comment]
Found a cleaner solution. 🙂

https://github.com/autofix-dev/autofix/blob/cb623ba90be0cd38aa3e9c58b3d765fafee66a86/autofix.js#L91-L93
